# Generated by Django 4.2.7 on 2023-12-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Regi',
        ),
    ]
