# Generated by Django 4.2.7 on 2023-12-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_register_regi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regi',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='regi',
            name='password',
            field=models.CharField(default=123455, max_length=50),
            preserve_default=False,
        ),
    ]
